<?php

namespace Database\Seeders;

use App\Models\Template;
use Illuminate\Database\Seeder;

/**
 * Seeds the nine modern, multi-page templates that complement Advocate Pro.
 * Every section uses a block registered in the visual page builder, so the
 * starter copy, repeaters, calls to action, and form embeds remain editable.
 */
class ModernTemplateSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->blueprints() as $blueprint) {
            $template = Template::updateOrCreate(
                ['slug' => $blueprint['slug']],
                [
                    'name' => $blueprint['name'],
                    'industry' => $blueprint['industry'],
                    'description' => $blueprint['description'],
                    'version' => '1.0.0',
                    'design_tokens' => [
                        'colors' => $blueprint['colors'],
                        'typography' => $blueprint['typography'],
                        'radius' => $blueprint['radius'],
                    ],
                    'default_settings' => [
                        'header' => [
                            'style' => $blueprint['header_style'],
                            'sticky' => true,
                            'show_language' => false,
                            'cta' => ['label' => $blueprint['primary_cta'], 'url' => '/contact'],
                        ],
                        'footer' => [
                            'company_info' => $blueprint['footer_text'],
                            'copyright' => '© '.date('Y').' Your Company. All rights reserved.',
                        ],
                    ],
                    'is_active' => true,
                ]
            );

            foreach ($this->layouts($blueprint) as $layout) {
                // Page type is the stable identity. This also upgrades the
                // original Healthcare Classic layouts without creating copies.
                $template->layouts()->updateOrCreate(
                    ['page_type' => $layout['page_type']],
                    ['name' => $layout['name'], 'structure' => $layout['structure']]
                );
            }
        }
    }

    private function layouts(array $template): array
    {
        $catalogPath = '/'.$template['catalog_type'];
        $glass = $template['glass_features'] ? 'glass' : 'standard';

        return [
            [
                'page_type' => 'home',
                'name' => 'Home',
                'structure' => [
                    ['block_type' => 'hero', 'default_settings' => ['variant' => 'centered'], 'default_content' => [
                        'badge' => $template['badge'],
                        'heading' => $template['hero_heading'],
                        'subheading' => $template['hero_subheading'],
                        'cta' => ['label' => $template['primary_cta'], 'url' => '/contact'],
                        'cta2' => ['label' => $template['secondary_cta'], 'url' => $catalogPath],
                    ]],
                    ['block_type' => 'stats', 'default_content' => ['items' => $template['stats']]],
                    ['block_type' => 'services_grid', 'default_settings' => ['variant' => $glass], 'default_content' => [
                        'heading' => $template['services_heading'],
                        'subheading' => $template['services_subheading'],
                        'items' => array_slice($template['services'], 0, 6),
                    ]],
                    ['block_type' => 'two_panel', 'default_content' => [
                        'heading' => $template['process_heading'],
                        'subheading' => $template['process_subheading'],
                        'panels' => $template['panels'],
                    ]],
                    ['block_type' => 'testimonials', 'default_content' => [
                        'heading' => $template['testimonials_heading'],
                        'items' => $template['testimonials'],
                    ]],
                    ['block_type' => 'faq', 'default_content' => [
                        'heading' => 'Questions, answered',
                        'items' => $template['faqs'],
                    ]],
                    ['block_type' => 'cta', 'default_content' => [
                        'heading' => $template['cta_heading'],
                        'subheading' => $template['cta_subheading'],
                        'cta' => ['label' => $template['primary_cta'], 'url' => '/contact'],
                    ]],
                ],
            ],
            [
                'page_type' => 'about',
                'name' => 'About',
                'structure' => [
                    ['block_type' => 'hero', 'default_settings' => ['variant' => 'compact'], 'default_content' => [
                        'badge' => $template['badge'],
                        'heading' => $template['about_heading'],
                        'subheading' => $template['about_subheading'],
                    ]],
                    ['block_type' => 'rich_text', 'default_content' => ['html' => $template['story']]],
                    ['block_type' => 'stats', 'default_content' => ['items' => $template['stats']]],
                    ['block_type' => 'team_grid', 'default_content' => [
                        'heading' => $template['team_heading'],
                        'items' => $template['team'],
                    ]],
                    ['block_type' => 'testimonials', 'default_content' => [
                        'heading' => $template['testimonials_heading'],
                        'items' => $template['testimonials'],
                    ]],
                    ['block_type' => 'cta', 'default_content' => [
                        'heading' => $template['cta_heading'],
                        'subheading' => $template['cta_subheading'],
                        'cta' => ['label' => $template['primary_cta'], 'url' => '/contact'],
                    ]],
                ],
            ],
            [
                'page_type' => $template['catalog_type'],
                'name' => $template['catalog_name'],
                'structure' => [
                    ['block_type' => 'hero', 'default_settings' => ['variant' => 'compact'], 'default_content' => [
                        'heading' => $template['catalog_heading'],
                        'subheading' => $template['services_subheading'],
                        'cta' => ['label' => $template['primary_cta'], 'url' => '/contact'],
                    ]],
                    ['block_type' => 'services_grid', 'default_settings' => ['variant' => 'standard'], 'default_content' => [
                        'heading' => $template['services_heading'],
                        'subheading' => $template['services_subheading'],
                        'items' => $template['services'],
                    ]],
                    ['block_type' => 'two_panel', 'default_content' => [
                        'heading' => $template['process_heading'],
                        'subheading' => $template['process_subheading'],
                        'panels' => $template['panels'],
                    ]],
                    ['block_type' => 'testimonials', 'default_content' => [
                        'heading' => $template['testimonials_heading'],
                        'items' => $template['testimonials'],
                    ]],
                    ['block_type' => 'faq', 'default_content' => [
                        'heading' => 'Good to know',
                        'items' => $template['faqs'],
                    ]],
                    ['block_type' => 'cta', 'default_content' => [
                        'heading' => $template['cta_heading'],
                        'subheading' => $template['cta_subheading'],
                        'cta' => ['label' => $template['primary_cta'], 'url' => '/contact'],
                    ]],
                ],
            ],
            [
                'page_type' => 'contact',
                'name' => 'Contact',
                'structure' => [
                    ['block_type' => 'hero', 'default_settings' => ['variant' => 'compact'], 'default_content' => [
                        'heading' => $template['contact_heading'],
                        'subheading' => $template['contact_subheading'],
                    ]],
                    ['block_type' => 'form_embed', 'default_content' => [
                        'heading' => $template['form_heading'],
                        'form_slug' => 'contact',
                    ]],
                    ['block_type' => 'rich_text', 'default_content' => ['html' => $template['contact_details']]],
                ],
            ],
        ];
    }

    private function blueprints(): array
    {
        return [
            [
                'slug' => 'healthcare-classic',
                'name' => 'Healthcare Classic',
                'industry' => 'healthcare',
                'description' => 'Calm, trust-led website for clinics, hospitals, and specialist practices.',
                'colors' => ['primary' => '#0f766e', 'secondary' => '#0f172a', 'accent' => '#5eead4'],
                'typography' => ['heading' => "Georgia, 'Times New Roman', serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '1rem',
                'header_style' => 'light',
                'glass_features' => false,
                'badge' => 'Thoughtful care, close to home',
                'hero_heading' => 'Modern medicine with a human touch',
                'hero_subheading' => 'Experienced specialists, coordinated care, and simple appointments for every stage of life.',
                'primary_cta' => 'Book an appointment',
                'secondary_cta' => 'Explore care',
                'services_heading' => 'Care built around you',
                'services_subheading' => 'From prevention to specialist treatment, our teams make every next step clear.',
                'services' => [
                    ['icon' => '🩺', 'title' => 'Primary care', 'text' => 'Everyday care, screenings, and long-term health plans.'],
                    ['icon' => '❤️', 'title' => 'Cardiology', 'text' => 'Evidence-led heart care from diagnosis through recovery.'],
                    ['icon' => '🧠', 'title' => 'Neurology', 'text' => 'Specialist assessment and treatment for neurological conditions.'],
                    ['icon' => '👶', 'title' => 'Paediatrics', 'text' => 'Reassuring care for children, teens, and their families.'],
                    ['icon' => '🦴', 'title' => 'Orthopaedics', 'text' => 'Mobility-focused care for joints, bones, and sports injuries.'],
                    ['icon' => '🌿', 'title' => 'Wellness', 'text' => 'Practical preventive programs tailored to your goals.'],
                ],
                'stats' => [
                    ['value' => '25+', 'label' => 'Specialist doctors'],
                    ['value' => '15k+', 'label' => 'Patients cared for'],
                    ['value' => '4.9/5', 'label' => 'Patient rating'],
                    ['value' => '7 days', 'label' => 'Appointments available'],
                ],
                'process_heading' => 'Care without the runaround',
                'process_subheading' => 'A simple path from first question to ongoing support.',
                'panels' => [
                    ['title' => 'Start with a conversation', 'text' => 'Tell us what you need and choose a convenient time.', 'points' => "Online appointment requests\nHelpful pre-visit guidance\nTransparent consultation fees"],
                    ['title' => 'Leave with a clear plan', 'text' => 'Your care team coordinates the details and keeps you informed.', 'points' => "Plain-language next steps\nDigital reports and prescriptions\nCoordinated follow-up care"],
                ],
                'testimonials_heading' => 'Patients feel the difference',
                'testimonials' => [
                    ['quote' => 'I felt heard, never rushed, and left knowing exactly what to do next.', 'name' => 'Maya R.'],
                    ['quote' => 'The entire visit was calm, punctual, and thoughtfully organised.', 'name' => 'David K.'],
                    ['quote' => 'Every specialist had the full picture. I did not have to repeat my story.', 'name' => 'Anita S.'],
                ],
                'faqs' => [
                    ['question' => 'Can I request an appointment online?', 'answer' => 'Yes. Send your preferred date and department and our care team will confirm the best available slot.'],
                    ['question' => 'Do you offer video consultations?', 'answer' => 'Selected departments offer secure video consultations for follow-ups and suitable first visits.'],
                    ['question' => 'What should I bring?', 'answer' => 'Bring identification, current prescriptions, and any reports that may help your doctor understand your history.'],
                ],
                'about_heading' => 'Healthcare that sees the whole person',
                'about_subheading' => 'Clinical excellence, clear communication, and care designed around real lives.',
                'story' => '<h2>Care should feel coordinated</h2><p>We bring experienced clinicians, modern diagnostics, and responsive support together under one roof. Our model is built to reduce uncertainty and give every patient a clear path forward.</p><p>Use the page builder to replace this starter story with your history, accreditations, facilities, and approach to care.</p>',
                'team_heading' => 'Meet your care leaders',
                'team' => [
                    ['name' => 'Dr. Maya Patel', 'role' => 'Medical Director', 'image' => ''],
                    ['name' => 'Dr. Aaron Lee', 'role' => 'Head of Cardiology', 'image' => ''],
                    ['name' => 'Dr. Sofia Khan', 'role' => 'Consultant Paediatrician', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Departments',
                'catalog_heading' => 'Specialist care, connected',
                'cta_heading' => 'Ready to feel better?',
                'cta_subheading' => 'Request an appointment and our care team will help you find the right specialist.',
                'contact_heading' => 'How can we help?',
                'contact_subheading' => 'Share a few details and our team will respond within one working day.',
                'form_heading' => 'Request an appointment',
                'contact_details' => '<h2>Visit the clinic</h2><p>Add your address, phone number, opening hours, parking details, and emergency guidance here.</p>',
                'footer_text' => 'Clear, coordinated healthcare for every stage of life.',
            ],
            [
                'slug' => 'launchpad-saas',
                'name' => 'LaunchPad SaaS',
                'industry' => 'technology',
                'description' => 'Conversion-ready product site for SaaS startups and technology companies.',
                'colors' => ['primary' => '#6d28d9', 'secondary' => '#111827', 'accent' => '#a7f3d0'],
                'typography' => ['heading' => "'Trebuchet MS', 'Segoe UI', sans-serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '1.25rem',
                'header_style' => 'dark',
                'glass_features' => true,
                'badge' => 'Ship better work, every week',
                'hero_heading' => 'One workspace for your fastest-moving teams',
                'hero_subheading' => 'Plan, automate, and measure the work that moves your product forward—without adding another layer of meetings.',
                'primary_cta' => 'Start free',
                'secondary_cta' => 'See the platform',
                'services_heading' => 'Everything your team needs to move',
                'services_subheading' => 'A flexible toolkit that connects strategy, delivery, and customer insight.',
                'services' => [
                    ['icon' => '⚡', 'title' => 'Fast workflows', 'text' => 'Turn repeatable processes into clear, automated flows.'],
                    ['icon' => '🧩', 'title' => 'Connected tools', 'text' => 'Bring your product stack together with flexible integrations.'],
                    ['icon' => '📈', 'title' => 'Live insights', 'text' => 'Understand progress, risk, and impact from one dashboard.'],
                    ['icon' => '🤝', 'title' => 'Team spaces', 'text' => 'Give every squad focus without creating information silos.'],
                    ['icon' => '🔐', 'title' => 'Enterprise security', 'text' => 'Protect work with granular access and audit-ready controls.'],
                    ['icon' => '✨', 'title' => 'Smart assistance', 'text' => 'Summarise, draft, and prioritise with context-aware AI.'],
                ],
                'stats' => [
                    ['value' => '40%', 'label' => 'Less admin work'],
                    ['value' => '2.4x', 'label' => 'Faster delivery'],
                    ['value' => '99.9%', 'label' => 'Platform uptime'],
                    ['value' => '80+', 'label' => 'Integrations'],
                ],
                'process_heading' => 'From signup to momentum',
                'process_subheading' => 'Start small, prove value quickly, then scale across teams.',
                'panels' => [
                    ['title' => 'Connect your workflow', 'text' => 'Import your work and tailor a proven starting point.', 'points' => "Guided workspace setup\nReady-made workflow templates\nNo-code integrations"],
                    ['title' => 'Scale what works', 'text' => 'Turn team habits into repeatable company systems.', 'points' => "Shared reporting standards\nPermissions for every role\nHands-on success support"],
                ],
                'testimonials_heading' => 'Built for teams with momentum',
                'testimonials' => [
                    ['quote' => 'We replaced three disconnected tools and finally have one source of truth.', 'name' => 'Nina, VP Product'],
                    ['quote' => 'Our weekly planning time dropped by half in the first month.', 'name' => 'Owen, COO'],
                    ['quote' => 'The team adopted it without a training marathon. That was the win.', 'name' => 'Priya, Head of Ops'],
                ],
                'faqs' => [
                    ['question' => 'Is there a free trial?', 'answer' => 'Yes. Teams can explore the complete platform before selecting a plan.'],
                    ['question' => 'Can we import existing work?', 'answer' => 'Yes. Use CSV import or supported integrations to bring projects, users, and key fields across.'],
                    ['question' => 'Does it support enterprise access controls?', 'answer' => 'Enterprise plans include advanced roles, SSO options, audit history, and guided rollout support.'],
                ],
                'about_heading' => 'Software should create clarity',
                'about_subheading' => 'We build tools that help ambitious teams spend more time making and less time managing.',
                'story' => '<h2>Built for the way modern teams move</h2><p>LaunchPad began with a familiar frustration: talented teams were losing momentum to disconnected tools and status meetings. We designed a calmer workspace where priorities, ownership, and outcomes stay visible.</p><p>Replace this starter copy with your founding story, product philosophy, investor milestones, and the customer problem you are solving.</p>',
                'team_heading' => 'Meet the builders',
                'team' => [
                    ['name' => 'Alex Morgan', 'role' => 'Co-founder & CEO', 'image' => ''],
                    ['name' => 'Isha Rao', 'role' => 'Co-founder & Product', 'image' => ''],
                    ['name' => 'Marcus Chen', 'role' => 'VP Engineering', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Platform',
                'catalog_heading' => 'A platform that grows with your team',
                'cta_heading' => 'Make your next week your clearest yet',
                'cta_subheading' => 'Start with a ready-made workspace and invite your team in minutes.',
                'contact_heading' => 'Let’s talk about your workflow',
                'contact_subheading' => 'Tell us about your team and we will point you to the right setup.',
                'form_heading' => 'Talk to sales',
                'contact_details' => '<h2>Need product support?</h2><p>Add links to your help centre, system status, sales email, and regional office details here.</p>',
                'footer_text' => 'The connected workspace for teams that ship.',
            ],
            [
                'slug' => 'studio-north',
                'name' => 'Studio North',
                'industry' => 'agency',
                'description' => 'Editorial portfolio template for creative studios, agencies, and freelancers.',
                'colors' => ['primary' => '#ea580c', 'secondary' => '#18181b', 'accent' => '#fde047'],
                'typography' => ['heading' => "Georgia, 'Times New Roman', serif", 'body' => 'Arial, Helvetica, sans-serif'],
                'radius' => '0.25rem',
                'header_style' => 'light',
                'glass_features' => false,
                'badge' => 'Independent creative studio',
                'hero_heading' => 'Brands with a point of view',
                'hero_subheading' => 'Strategy, identity, and digital experiences for organisations ready to look and sound unmistakably themselves.',
                'primary_cta' => 'Start a project',
                'secondary_cta' => 'View our work',
                'services_heading' => 'Big-picture thinking, beautifully made',
                'services_subheading' => 'A senior creative team from the first workshop through the final launch.',
                'services' => [
                    ['icon' => '✦', 'title' => 'Brand strategy', 'text' => 'Positioning and language that make every decision sharper.'],
                    ['icon' => '◐', 'title' => 'Visual identity', 'text' => 'Flexible identity systems built to be used, not admired in a deck.'],
                    ['icon' => '↗', 'title' => 'Digital design', 'text' => 'Web experiences that pair strong stories with effortless journeys.'],
                    ['icon' => 'Aa', 'title' => 'Campaigns', 'text' => 'Launch ideas that travel across channels without losing character.'],
                    ['icon' => '◎', 'title' => 'Motion', 'text' => 'Purposeful movement that makes brands feel alive.'],
                    ['icon' => '□', 'title' => 'Design systems', 'text' => 'Reusable foundations that keep growing teams consistent.'],
                ],
                'stats' => [
                    ['value' => '42', 'label' => 'Brands launched'],
                    ['value' => '11', 'label' => 'Design awards'],
                    ['value' => '9 yrs', 'label' => 'Working together'],
                    ['value' => '6', 'label' => 'Countries served'],
                ],
                'process_heading' => 'Collaborative by design',
                'process_subheading' => 'A focused process with room for discovery, debate, and the unexpected.',
                'panels' => [
                    ['title' => 'Find the sharp idea', 'text' => 'We align on the problem before reaching for the pixels.', 'points' => "Stakeholder workshops\nAudience and category research\nA clear creative brief"],
                    ['title' => 'Build it to last', 'text' => 'We turn the idea into a flexible, usable system.', 'points' => "Rapid concept rounds\nReal-world prototyping\nPractical launch toolkit"],
                ],
                'testimonials_heading' => 'Good work starts with trust',
                'testimonials' => [
                    ['quote' => 'They found the idea we had been trying to articulate for years.', 'name' => 'Leah, Founder'],
                    ['quote' => 'Every review was focused. Every decision made the work stronger.', 'name' => 'Tom, Marketing Director'],
                    ['quote' => 'The new system feels bold, useful, and completely ours.', 'name' => 'Sana, Head of Brand'],
                ],
                'faqs' => [
                    ['question' => 'What size projects do you take on?', 'answer' => 'We work best on focused identity, campaign, and digital projects with direct access to decision-makers.'],
                    ['question' => 'Do you work with in-house teams?', 'answer' => 'Yes. We often partner closely with internal brand, marketing, and product teams.'],
                    ['question' => 'How long does a project take?', 'answer' => 'Most engagements run from six to sixteen weeks, depending on scope and stakeholder availability.'],
                ],
                'about_heading' => 'Small team. Wide perspective.',
                'about_subheading' => 'Independent, senior-led, and interested in work that changes how people see things.',
                'story' => '<h2>We make the complicated feel inevitable</h2><p>Studio North is an independent design practice bringing strategy and craft into the same conversation. Our small senior team works directly with clients, so insight never gets lost between the briefing and the making.</p><p>Edit this page to share your own studio ethos, capabilities, collaborators, and recognitions.</p>',
                'team_heading' => 'The studio',
                'team' => [
                    ['name' => 'Noah Bell', 'role' => 'Creative Director', 'image' => ''],
                    ['name' => 'Amina Yusuf', 'role' => 'Strategy Director', 'image' => ''],
                    ['name' => 'June Park', 'role' => 'Design Lead', 'image' => ''],
                ],
                'catalog_type' => 'portfolio',
                'catalog_name' => 'Selected Work',
                'catalog_heading' => 'Work that earns attention',
                'cta_heading' => 'Have something interesting in mind?',
                'cta_subheading' => 'Tell us what is changing, what is stuck, and what success should feel like.',
                'contact_heading' => 'Start with the interesting part',
                'contact_subheading' => 'A short brief is perfect. We will come back with useful questions.',
                'form_heading' => 'Tell us about your project',
                'contact_details' => '<h2>Studio details</h2><p>Add your studio address, new-business email, availability, and social links here.</p>',
                'footer_text' => 'Independent strategy and design for brands with ambition.',
            ],
            [
                'slug' => 'ember-and-sage',
                'name' => 'Ember & Sage',
                'industry' => 'restaurant',
                'description' => 'Warm, atmospheric template for restaurants, cafés, and culinary concepts.',
                'colors' => ['primary' => '#9a3412', 'secondary' => '#292524', 'accent' => '#fbbf24'],
                'typography' => ['heading' => "'Palatino Linotype', Palatino, Georgia, serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '0.75rem',
                'header_style' => 'dark',
                'glass_features' => true,
                'badge' => 'Seasonal plates · Open fire · Good company',
                'hero_heading' => 'A table worth gathering around',
                'hero_subheading' => 'Ingredient-led cooking, generous hospitality, and a menu shaped by the farms and seasons around us.',
                'primary_cta' => 'Reserve a table',
                'secondary_cta' => 'Explore the menu',
                'services_heading' => 'Come hungry, leave connected',
                'services_subheading' => 'From quiet lunches to long celebrations, every service is made to feel personal.',
                'services' => [
                    ['icon' => '🔥', 'title' => 'Open-fire kitchen', 'text' => 'Vegetables, seafood, and meats cooked over flame and embers.'],
                    ['icon' => '🌾', 'title' => 'Seasonal menu', 'text' => 'A living menu built around what local growers bring us.'],
                    ['icon' => '🍷', 'title' => 'Thoughtful cellar', 'text' => 'Low-intervention bottles and generous by-the-glass pours.'],
                    ['icon' => '🥬', 'title' => 'Plant-forward plates', 'text' => 'Vegetarian choices designed with the same care as every dish.'],
                    ['icon' => '🎉', 'title' => 'Private dining', 'text' => 'Intimate celebrations with flexible sharing menus.'],
                    ['icon' => '☀️', 'title' => 'Weekend brunch', 'text' => 'Slow mornings, fresh bakes, and seasonal favourites.'],
                ],
                'stats' => [
                    ['value' => '12', 'label' => 'Local farm partners'],
                    ['value' => '4.8/5', 'label' => 'Guest rating'],
                    ['value' => '6 days', 'label' => 'Open each week'],
                    ['value' => '1 table', 'label' => 'Saved for walk-ins'],
                ],
                'process_heading' => 'From the field to your table',
                'process_subheading' => 'The menu begins with relationships and ends with a plate that feels of the moment.',
                'panels' => [
                    ['title' => 'Choose with the season', 'text' => 'We buy close to home and let the best ingredients lead.', 'points' => "Direct farm relationships\nWhole-animal and root-to-leaf cooking\nMenus that change naturally"],
                    ['title' => 'Cook with intention', 'text' => 'Simple techniques, open fire, and no unnecessary fuss.', 'points' => "Made from scratch each day\nDietary needs welcomed\nWarm, knowledgeable service"],
                ],
                'testimonials_heading' => 'Notes from our guests',
                'testimonials' => [
                    ['quote' => 'Every plate felt generous and surprising without trying too hard.', 'name' => 'Mira K.'],
                    ['quote' => 'The kind of place where a quick dinner happily becomes three hours.', 'name' => 'Jon R.'],
                    ['quote' => 'They handled every dietary request with genuine care.', 'name' => 'Elena P.'],
                ],
                'faqs' => [
                    ['question' => 'Do you welcome walk-ins?', 'answer' => 'Yes. We hold a small number of seats each service for walk-in guests.'],
                    ['question' => 'Can you accommodate dietary requirements?', 'answer' => 'Please share your needs when booking. The kitchen can accommodate many common requirements with advance notice.'],
                    ['question' => 'Do you host private events?', 'answer' => 'Our private room is available for intimate lunches, dinners, and celebrations with a tailored menu.'],
                ],
                'about_heading' => 'Cooking rooted in place',
                'about_subheading' => 'A neighbourhood restaurant built on patient sourcing, expressive cooking, and warm hospitality.',
                'story' => '<h2>Good food begins before the kitchen</h2><p>Ember & Sage grew from a belief that restaurants are at their best when they belong to their place. We work closely with nearby growers, millers, fishers, and makers, then cook their ingredients with restraint over flame.</p><p>Use the builder to tell your restaurant story, introduce the chef, and share your sourcing philosophy.</p>',
                'team_heading' => 'The people behind the pass',
                'team' => [
                    ['name' => 'Chef Theo Martin', 'role' => 'Chef & Co-owner', 'image' => ''],
                    ['name' => 'Lina Bose', 'role' => 'Restaurant Director', 'image' => ''],
                    ['name' => 'Rafael Costa', 'role' => 'Head Sommelier', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Menu & Dining',
                'catalog_heading' => 'What’s on the table',
                'cta_heading' => 'Your table is waiting',
                'cta_subheading' => 'Join us for a seasonal menu, a good bottle, and an unhurried evening.',
                'contact_heading' => 'Plan your visit',
                'contact_subheading' => 'Book a table, ask about a celebration, or send the team a note.',
                'form_heading' => 'Reserve or enquire',
                'contact_details' => '<h2>Find us</h2><p>Add your address, service hours, parking or transit notes, reservation policy, and phone number here.</p>',
                'footer_text' => 'Seasonal cooking over fire, served with warmth.',
            ],
            [
                'slug' => 'haven-realty',
                'name' => 'Haven Realty',
                'industry' => 'real estate',
                'description' => 'Polished, lead-focused template for property agencies and independent agents.',
                'colors' => ['primary' => '#065f46', 'secondary' => '#172554', 'accent' => '#fcd34d'],
                'typography' => ['heading' => "Georgia, 'Times New Roman', serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '0.5rem',
                'header_style' => 'light',
                'glass_features' => false,
                'badge' => 'Local knowledge. Better moves.',
                'hero_heading' => 'Find the place your next chapter begins',
                'hero_subheading' => 'Clear advice and exceptional marketing for buyers, sellers, and investors across the city’s most liveable neighbourhoods.',
                'primary_cta' => 'Book a consultation',
                'secondary_cta' => 'Explore properties',
                'services_heading' => 'Every move, expertly handled',
                'services_subheading' => 'Local market insight and calm guidance from first conversation to final key.',
                'services' => [
                    ['icon' => '🏡', 'title' => 'Buy a home', 'text' => 'Shortlists, private viewings, and negotiation grounded in data.'],
                    ['icon' => '🔑', 'title' => 'Sell with confidence', 'text' => 'Positioning and marketing that brings the right buyers forward.'],
                    ['icon' => '🏙️', 'title' => 'New developments', 'text' => 'Early access and clear comparisons across new-build opportunities.'],
                    ['icon' => '📊', 'title' => 'Property investment', 'text' => 'Practical guidance on yield, demand, and long-term potential.'],
                    ['icon' => '📍', 'title' => 'Relocation', 'text' => 'Neighbourhood orientation and a smoother move from anywhere.'],
                    ['icon' => '✦', 'title' => 'Home valuation', 'text' => 'A considered market assessment, not an automated guess.'],
                ],
                'stats' => [
                    ['value' => '320+', 'label' => 'Homes matched'],
                    ['value' => '97%', 'label' => 'Asking price achieved'],
                    ['value' => '18 yrs', 'label' => 'Local experience'],
                    ['value' => '4.9/5', 'label' => 'Client rating'],
                ],
                'process_heading' => 'A calmer way to move',
                'process_subheading' => 'Good decisions come from clear information and an advisor who stays one step ahead.',
                'panels' => [
                    ['title' => 'Understand the opportunity', 'text' => 'We start with your priorities, timing, and non-negotiables.', 'points' => "Honest market appraisal\nNeighbourhood-level insight\nA clear plan and timeline"],
                    ['title' => 'Move with confidence', 'text' => 'We manage the details and keep every party progressing.', 'points' => "Skilled offer negotiation\nProactive transaction updates\nSupport through completion"],
                ],
                'testimonials_heading' => 'Moves made memorable',
                'testimonials' => [
                    ['quote' => 'They understood what we needed before we could quite put it into words.', 'name' => 'The Mehta family'],
                    ['quote' => 'Our sale felt organised from day one, and the result exceeded our target.', 'name' => 'Clara J.'],
                    ['quote' => 'Every update was useful and honest. We never had to chase.', 'name' => 'Ben & Tariq'],
                ],
                'faqs' => [
                    ['question' => 'How do you value a property?', 'answer' => 'We combine recent local evidence, current buyer demand, property condition, and first-hand neighbourhood knowledge.'],
                    ['question' => 'Can you help us buy before we sell?', 'answer' => 'Yes. We will map the financial and timing options, then shape a coordinated search and sale plan.'],
                    ['question' => 'Do you work with investors?', 'answer' => 'Yes. We advise on acquisition, local demand, rental potential, and long-term exit considerations.'],
                ],
                'about_heading' => 'Property advice with perspective',
                'about_subheading' => 'Independent, neighbourhood-led, and focused on the outcome that is right for you.',
                'story' => '<h2>We know more than the market</h2><p>Haven Realty pairs rigorous local data with the human context behind every move. We know which streets hold value, what buyers are responding to, and how to keep a complicated transaction on course.</p><p>Replace this copy with your agency history, service area, sales record, and approach to client care.</p>',
                'team_heading' => 'Your local property team',
                'team' => [
                    ['name' => 'Amelia Grant', 'role' => 'Managing Partner', 'image' => ''],
                    ['name' => 'Rohan Malik', 'role' => 'Sales Director', 'image' => ''],
                    ['name' => 'Eva Santos', 'role' => 'Buying Advisor', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Properties & Services',
                'catalog_heading' => 'Expertise for every kind of move',
                'cta_heading' => 'Thinking about your next move?',
                'cta_subheading' => 'Start with a no-pressure conversation about your goals and the current market.',
                'contact_heading' => 'Let’s talk property',
                'contact_subheading' => 'Tell us whether you are buying, selling, investing, or simply exploring.',
                'form_heading' => 'Book a property consultation',
                'contact_details' => '<h2>Visit the office</h2><p>Add your office address, neighbourhood coverage, opening hours, phone number, and property-alert signup details here.</p>',
                'footer_text' => 'Independent property advice for better moves.',
            ],
            [
                'slug' => 'learnsphere-academy',
                'name' => 'LearnSphere Academy',
                'industry' => 'education',
                'description' => 'Welcoming, outcomes-focused template for schools, academies, and course creators.',
                'colors' => ['primary' => '#1d4ed8', 'secondary' => '#172554', 'accent' => '#facc15'],
                'typography' => ['heading' => "'Trebuchet MS', 'Segoe UI', sans-serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '1rem',
                'header_style' => 'light',
                'glass_features' => true,
                'badge' => 'Learn with purpose',
                'hero_heading' => 'Skills that open new possibilities',
                'hero_subheading' => 'Live, practical learning led by experienced educators—built for curious people and ambitious careers.',
                'primary_cta' => 'Talk to admissions',
                'secondary_cta' => 'Explore programs',
                'services_heading' => 'Learning designed for progress',
                'services_subheading' => 'Structured programs, active practice, and support that continues beyond the classroom.',
                'services' => [
                    ['icon' => '💻', 'title' => 'Digital skills', 'text' => 'Build practical technology fluency through real projects.'],
                    ['icon' => '📊', 'title' => 'Business & leadership', 'text' => 'Make better decisions and lead modern teams with confidence.'],
                    ['icon' => '🎨', 'title' => 'Design & creativity', 'text' => 'Turn ideas into thoughtful, portfolio-ready work.'],
                    ['icon' => '🗣️', 'title' => 'Communication', 'text' => 'Write, present, and collaborate with clarity and influence.'],
                    ['icon' => '🌍', 'title' => 'Language learning', 'text' => 'Develop useful fluency through conversation-first teaching.'],
                    ['icon' => '🚀', 'title' => 'Career accelerators', 'text' => 'Focused pathways with mentoring and interview practice.'],
                ],
                'stats' => [
                    ['value' => '12k+', 'label' => 'Learners supported'],
                    ['value' => '94%', 'label' => 'Program completion'],
                    ['value' => '60+', 'label' => 'Expert instructors'],
                    ['value' => '4.8/5', 'label' => 'Learner rating'],
                ],
                'process_heading' => 'A clear path from interest to impact',
                'process_subheading' => 'Learn by doing, get useful feedback, and leave with evidence of what you can do.',
                'panels' => [
                    ['title' => 'Learn actively', 'text' => 'Short lessons create space for discussion, practice, and feedback.', 'points' => "Live expert instruction\nHands-on weekly projects\nSmall peer learning groups"],
                    ['title' => 'Apply confidently', 'text' => 'Turn new knowledge into work you can show and use.', 'points' => "Portfolio-ready outcomes\nOne-to-one mentor feedback\nCareer and next-step guidance"],
                ],
                'testimonials_heading' => 'Progress in their own words',
                'testimonials' => [
                    ['quote' => 'I used what I learned in my job the very next week.', 'name' => 'Meera, Product Manager'],
                    ['quote' => 'The feedback was specific, kind, and genuinely improved my work.', 'name' => 'Daniel, Designer'],
                    ['quote' => 'I left with a portfolio and the confidence to change careers.', 'name' => 'Fatima, Graduate'],
                ],
                'faqs' => [
                    ['question' => 'Are classes live or recorded?', 'answer' => 'Programs combine live sessions with recordings and self-paced practice, so learners can review key material.'],
                    ['question' => 'Do I need prior experience?', 'answer' => 'Each program lists its starting level clearly. Many pathways are designed specifically for beginners.'],
                    ['question' => 'Is financial support available?', 'answer' => 'Selected programs offer instalment plans, scholarships, or employer sponsorship guidance.'],
                ],
                'about_heading' => 'Education built for real life',
                'about_subheading' => 'Curious classrooms, experienced teachers, and outcomes learners can carry forward.',
                'story' => '<h2>Learning changes when it feels useful</h2><p>LearnSphere brings expert teaching and active practice together. Our programs are intentionally focused: enough structure to keep momentum, enough support to work through difficulty, and enough realism to make every lesson count.</p><p>Edit this page to add your educational philosophy, accreditations, campus or online model, and learner outcomes.</p>',
                'team_heading' => 'Meet our academic team',
                'team' => [
                    ['name' => 'Dr. Kavya Menon', 'role' => 'Academic Director', 'image' => ''],
                    ['name' => 'Luis Romero', 'role' => 'Head of Digital Programs', 'image' => ''],
                    ['name' => 'Hannah Wu', 'role' => 'Learner Experience Lead', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Programs',
                'catalog_heading' => 'Find your next learning path',
                'cta_heading' => 'What could you learn next?',
                'cta_subheading' => 'Talk with admissions about your goals and the program that fits them best.',
                'contact_heading' => 'Plan your next step',
                'contact_subheading' => 'Ask about programs, schedules, fees, or the learning experience.',
                'form_heading' => 'Talk to admissions',
                'contact_details' => '<h2>Admissions information</h2><p>Add campus details, office hours, application dates, phone numbers, and student-support links here.</p>',
                'footer_text' => 'Practical learning for ambitious, curious people.',
            ],
            [
                'slug' => 'commerce-bloom',
                'name' => 'Commerce Bloom',
                'industry' => 'ecommerce',
                'description' => 'Bright, editorial storefront for modern product and lifestyle brands.',
                'colors' => ['primary' => '#be123c', 'secondary' => '#3f1d2e', 'accent' => '#fda4af'],
                'typography' => ['heading' => "'Palatino Linotype', Palatino, Georgia, serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '1.5rem',
                'header_style' => 'light',
                'glass_features' => false,
                'badge' => 'Small rituals, beautifully made',
                'hero_heading' => 'Everyday objects with a little more joy',
                'hero_subheading' => 'Thoughtfully designed home and lifestyle pieces made in small batches from responsible materials.',
                'primary_cta' => 'Ask a question',
                'secondary_cta' => 'Shop the collection',
                'services_heading' => 'Designed for daily life',
                'services_subheading' => 'Useful forms, expressive colour, and materials chosen with care.',
                'services' => [
                    ['icon' => '🏺', 'title' => 'Table & kitchen', 'text' => 'Tactile pieces that make ordinary meals feel considered.'],
                    ['icon' => '🕯️', 'title' => 'Home fragrance', 'text' => 'Layered scents poured in reusable vessels.'],
                    ['icon' => '🧺', 'title' => 'Soft goods', 'text' => 'Natural-fibre textiles in easy, lasting colours.'],
                    ['icon' => '✏️', 'title' => 'Desk essentials', 'text' => 'Tools and organisers for calmer, more creative work.'],
                    ['icon' => '🎁', 'title' => 'Ready to gift', 'text' => 'Thoughtful sets, beautiful wrapping, and personal notes.'],
                    ['icon' => '♻️', 'title' => 'Refill & renew', 'text' => 'Refills and replacement parts that extend product life.'],
                ],
                'stats' => [
                    ['value' => '85%', 'label' => 'Lower-impact materials'],
                    ['value' => '4.9/5', 'label' => 'Customer rating'],
                    ['value' => '30 days', 'label' => 'Easy returns'],
                    ['value' => '48 hrs', 'label' => 'Dispatch target'],
                ],
                'process_heading' => 'Made slowly, sent thoughtfully',
                'process_subheading' => 'We pay attention to the whole product journey, not only the finished object.',
                'panels' => [
                    ['title' => 'Design with purpose', 'text' => 'Every detail earns its place through usefulness or delight.', 'points' => "Responsible material choices\nSmall-batch production\nRepairable where possible"],
                    ['title' => 'Deliver with care', 'text' => 'Packaging and support should feel as considered as the product.', 'points' => "Plastic-light packaging\nFast, human customer care\nSimple returns and exchanges"],
                ],
                'testimonials_heading' => 'Loved in real homes',
                'testimonials' => [
                    ['quote' => 'Even the packaging felt thoughtful. The piece is beautiful and genuinely useful.', 'name' => 'Ava L.'],
                    ['quote' => 'The colour is even better in person, and delivery was incredibly quick.', 'name' => 'Sam P.'],
                    ['quote' => 'Customer care solved my issue in one friendly message.', 'name' => 'Rina D.'],
                ],
                'faqs' => [
                    ['question' => 'When will my order ship?', 'answer' => 'In-stock items typically leave our studio within two working days.'],
                    ['question' => 'Can I return an item?', 'answer' => 'Unused items can be returned within 30 days. Add your exact policy and exceptions here.'],
                    ['question' => 'Do you offer gift wrapping?', 'answer' => 'Yes. Select gift wrapping and add a message during checkout, where available.'],
                ],
                'about_heading' => 'Objects with a longer point of view',
                'about_subheading' => 'Useful, expressive things made with respect for materials, makers, and the homes they enter.',
                'story' => '<h2>Buy less. Love it longer.</h2><p>Commerce Bloom creates everyday objects that bring usefulness and personality together. We work in small batches, choose materials carefully, and keep product lives in mind from the first sketch.</p><p>Replace this story with your brand origin, maker partnerships, sourcing standards, and impact commitments.</p>',
                'team_heading' => 'Made by a small team',
                'team' => [
                    ['name' => 'Mila Hart', 'role' => 'Founder & Creative Director', 'image' => ''],
                    ['name' => 'Neel Shah', 'role' => 'Product & Sourcing', 'image' => ''],
                    ['name' => 'Jade Cooper', 'role' => 'Customer Experience', 'image' => ''],
                ],
                'catalog_type' => 'products',
                'catalog_name' => 'Shop Collection',
                'catalog_heading' => 'Find your new everyday favourite',
                'cta_heading' => 'Need help choosing?',
                'cta_subheading' => 'Ask about materials, care, gifting, or which piece fits your space.',
                'contact_heading' => 'We’re here to help',
                'contact_subheading' => 'Questions about an item, order, return, or collaboration are always welcome.',
                'form_heading' => 'Send us a note',
                'contact_details' => '<h2>Customer care</h2><p>Add support hours, shipping regions, returns links, wholesale contact, and studio address here.</p>',
                'footer_text' => 'Thoughtful goods for brighter everyday rituals.',
            ],
            [
                'slug' => 'peakform-fitness',
                'name' => 'PeakForm Fitness',
                'industry' => 'fitness',
                'description' => 'High-energy membership template for gyms, trainers, and wellness studios.',
                'colors' => ['primary' => '#e11d48', 'secondary' => '#111827', 'accent' => '#bef264'],
                'typography' => ['heading' => "Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '0.5rem',
                'header_style' => 'dark',
                'glass_features' => true,
                'badge' => 'Train smart · Move strong · Feel ready',
                'hero_heading' => 'Build strength that shows up everywhere',
                'hero_subheading' => 'Expert coaching, energising classes, and a genuinely supportive community—whatever your starting point.',
                'primary_cta' => 'Claim a free session',
                'secondary_cta' => 'Explore training',
                'services_heading' => 'Your goals, more ways to reach them',
                'services_subheading' => 'Flexible training options built around progress, consistency, and real life.',
                'services' => [
                    ['icon' => '🏋️', 'title' => 'Strength training', 'text' => 'Progressive coaching for technique, confidence, and power.'],
                    ['icon' => '⚡', 'title' => 'HIIT classes', 'text' => 'Efficient, scalable sessions with energy to spare.'],
                    ['icon' => '🧘', 'title' => 'Mobility & recovery', 'text' => 'Move better, recover well, and keep training consistently.'],
                    ['icon' => '🎯', 'title' => 'Personal coaching', 'text' => 'One-to-one plans shaped around your body and schedule.'],
                    ['icon' => '👥', 'title' => 'Small groups', 'text' => 'Individual attention with the momentum of a team.'],
                    ['icon' => '🥗', 'title' => 'Nutrition habits', 'text' => 'Practical support for fuelling performance without extremes.'],
                ],
                'stats' => [
                    ['value' => '45+', 'label' => 'Weekly classes'],
                    ['value' => '12', 'label' => 'Expert coaches'],
                    ['value' => '4.9/5', 'label' => 'Member rating'],
                    ['value' => '7 days', 'label' => 'Open every week'],
                ],
                'process_heading' => 'A plan you can actually stick with',
                'process_subheading' => 'Start where you are, learn the fundamentals, and build sustainable momentum.',
                'panels' => [
                    ['title' => 'Know your starting point', 'text' => 'Your first session turns goals into a realistic plan.', 'points' => "Friendly movement assessment\nClear weekly recommendation\nScalable starting sessions"],
                    ['title' => 'Progress with support', 'text' => 'Coaches notice, adapt, and keep you moving forward.', 'points' => "Regular progress check-ins\nTechnique-first coaching\nA community that knows your name"],
                ],
                'testimonials_heading' => 'Stronger stories',
                'testimonials' => [
                    ['quote' => 'For the first time, I understand what I am doing and why it works.', 'name' => 'Lena, member for 8 months'],
                    ['quote' => 'The coaches make every session challenging without making it intimidating.', 'name' => 'Arjun, small-group member'],
                    ['quote' => 'I came for strength and stayed for the people.', 'name' => 'Chris, member for 2 years'],
                ],
                'faqs' => [
                    ['question' => 'Do I need to be fit before I join?', 'answer' => 'No. Every session can be scaled, and your coach will help you start at an appropriate level.'],
                    ['question' => 'What should I bring to my first session?', 'answer' => 'Comfortable training clothes, water, and any relevant health information for your coach.'],
                    ['question' => 'Can I try a class first?', 'answer' => 'Yes. Use the contact form to request an introductory session or studio tour.'],
                ],
                'about_heading' => 'Coaching changes everything',
                'about_subheading' => 'A welcoming training space where expert guidance and everyday consistency matter more than ego.',
                'story' => '<h2>Training should make life feel bigger</h2><p>PeakForm was built for people who want to feel capable, not punished. Our coaches teach the why behind every movement, celebrate patient progress, and shape sessions around the humans in front of them.</p><p>Edit this section with your gym story, coaching philosophy, facilities, and membership approach.</p>',
                'team_heading' => 'Meet your coaches',
                'team' => [
                    ['name' => 'Tara Singh', 'role' => 'Head Coach', 'image' => ''],
                    ['name' => 'Mike Evans', 'role' => 'Strength & Conditioning', 'image' => ''],
                    ['name' => 'Nora James', 'role' => 'Mobility & Recovery', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Training',
                'catalog_heading' => 'Find the way you like to train',
                'cta_heading' => 'Your first session is on us',
                'cta_subheading' => 'Meet a coach, see the space, and leave with a clear next step.',
                'contact_heading' => 'Come say hello',
                'contact_subheading' => 'Tell us what you want from training and we will help you choose a great first session.',
                'form_heading' => 'Claim your free session',
                'contact_details' => '<h2>Visit the gym</h2><p>Add your location, staffed hours, parking details, what to bring, and membership contact information here.</p>',
                'footer_text' => 'Expert coaching for strength that lasts.',
            ],
            [
                'slug' => 'finora-advisory',
                'name' => 'Finora Advisory',
                'industry' => 'finance',
                'description' => 'Confident, refined template for financial advisors and professional services firms.',
                'colors' => ['primary' => '#1e3a8a', 'secondary' => '#0f172a', 'accent' => '#c4b5fd'],
                'typography' => ['heading' => "Georgia, 'Times New Roman', serif", 'body' => "system-ui, -apple-system, 'Segoe UI', sans-serif"],
                'radius' => '0.75rem',
                'header_style' => 'dark',
                'glass_features' => false,
                'badge' => 'Clarity for every financial decision',
                'hero_heading' => 'A plan for the life behind the numbers',
                'hero_subheading' => 'Independent advice that brings your money, priorities, and long-term decisions into one clear view.',
                'primary_cta' => 'Schedule a conversation',
                'secondary_cta' => 'Explore our advice',
                'services_heading' => 'Advice that connects the whole picture',
                'services_subheading' => 'Thoughtful planning for today’s decisions and tomorrow’s possibilities.',
                'services' => [
                    ['icon' => '🧭', 'title' => 'Financial planning', 'text' => 'A practical roadmap connecting goals, cash flow, and choices.'],
                    ['icon' => '📈', 'title' => 'Investment advice', 'text' => 'Evidence-led portfolios aligned with risk and time horizon.'],
                    ['icon' => '🌅', 'title' => 'Retirement planning', 'text' => 'Turn future income needs into a confident, adaptable strategy.'],
                    ['icon' => '🛡️', 'title' => 'Protection planning', 'text' => 'Safeguards for the people, income, and plans that matter.'],
                    ['icon' => '🏢', 'title' => 'Business owners', 'text' => 'Coordinate company, family, succession, and personal wealth decisions.'],
                    ['icon' => '🌱', 'title' => 'Legacy planning', 'text' => 'Structure giving and wealth transfer around your intentions.'],
                ],
                'stats' => [
                    ['value' => '22 yrs', 'label' => 'Advisory experience'],
                    ['value' => '450+', 'label' => 'Families advised'],
                    ['value' => '96%', 'label' => 'Client retention'],
                    ['value' => '100%', 'label' => 'Independent advice'],
                ],
                'process_heading' => 'Complexity, made navigable',
                'process_subheading' => 'A disciplined process that keeps the conversation grounded in your real priorities.',
                'panels' => [
                    ['title' => 'Build the complete picture', 'text' => 'We listen first, then organise every moving part.', 'points' => "Goals and priorities discovery\nCash-flow and risk review\nA plain-language action plan"],
                    ['title' => 'Keep the plan alive', 'text' => 'Regular reviews help your strategy adapt as life changes.', 'points' => "Ongoing portfolio oversight\nProactive planning checkpoints\nCoordination with other professionals"],
                ],
                'testimonials_heading' => 'Confidence is the outcome',
                'testimonials' => [
                    ['quote' => 'For the first time, our financial decisions feel connected instead of reactive.', 'name' => 'Private client'],
                    ['quote' => 'They explain complexity without ever talking down to us.', 'name' => 'Business owner'],
                    ['quote' => 'The plan gave us permission to enjoy retirement, not just prepare for it.', 'name' => 'Retired couple'],
                ],
                'faqs' => [
                    ['question' => 'What happens in the first meeting?', 'answer' => 'We discuss what matters to you, the decisions ahead, and whether our approach is a good fit.'],
                    ['question' => 'How are fees structured?', 'answer' => 'Add your firm’s fee model here, including any initial planning and ongoing advice charges.'],
                    ['question' => 'Do you coordinate with accountants and lawyers?', 'answer' => 'Yes. With permission, we collaborate with your other professional advisors to keep recommendations aligned.'],
                ],
                'about_heading' => 'Independent advice. Enduring relationships.',
                'about_subheading' => 'Technical discipline and human conversation, brought together around what matters to you.',
                'story' => '<h2>Good advice creates room to decide</h2><p>Finora was founded to give clients one clear place to understand their financial life. We combine rigorous analysis with patient conversation, so every recommendation has a purpose you can see.</p><p>Use this page to add your firm history, regulatory disclosures, qualifications, advice philosophy, and client commitments.</p>',
                'team_heading' => 'Your advisory team',
                'team' => [
                    ['name' => 'Eleanor Price', 'role' => 'Managing Partner', 'image' => ''],
                    ['name' => 'Vikram Desai', 'role' => 'Chartered Financial Planner', 'image' => ''],
                    ['name' => 'Sophie Laurent', 'role' => 'Client Strategy Director', 'image' => ''],
                ],
                'catalog_type' => 'services',
                'catalog_name' => 'Our Advice',
                'catalog_heading' => 'Advice for the decisions that matter',
                'cta_heading' => 'Start with a clear conversation',
                'cta_subheading' => 'Tell us what is on your mind. The first meeting is about fit, not pressure.',
                'contact_heading' => 'What would you like clarity on?',
                'contact_subheading' => 'Share the decision or goal you are considering and our team will get in touch.',
                'form_heading' => 'Schedule an introductory call',
                'contact_details' => '<h2>Office and disclosures</h2><p>Add your office address, contact details, opening hours, regulatory status, and required risk notices here.</p>',
                'footer_text' => 'Independent financial advice for life in motion.',
            ],
        ];
    }
}
